# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@3.0.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    #machine: true
    executor:
      name: node/default
      tag: '12.18.2'
    steps:
      #- run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      #- run: nvm install 12.18.2
      #- run: npm install npm@latest -g
      - checkout
      - run: npm install
      - run: node -v
      #- run: npm run test
      #- run: npm i gitbook-cli 
      - run: npm run-script gitbook-build
      - run: npm run-script gitbook-version
      #- run: npm update gitbook-cli -g
      #- run: gitbook --version
      #- run: gitbook build
      #- run: gitbook serve

